### ISSUE TITLE
EMS Vehicles 

### ISSUE THREAD

**Issue by PreacherDeimos** [fkk-cz/noire_vehicles#1033]
Ever since the vehicles went to server side we have been having tremendous problems with our Ambulance and stretchers, when trying to attach a stretcher to the power loader that you push it back and forth to haul away the stretchers, it just doesn't want to attach half the time or it will tell someone near by something about "Can't attach to an entity" when you're not even the one using the stretcher, people are having to fly in and out multiple times to try fix this bug and bodies are falling from stretchers upon transporting them too. 

The F150 and F250 have absolutely NO grip at all, literally, please try to drive them if you can, they just spin like crazy, so please please fix that, give them all-wheel drive too as they're trucks and lastly, The Chevy Tahoe we have is front wheel drive for some reason, handles pretty poorly. Could you please make it rear wheel or all-wheel drive as it is a 4X4 vehicle? Thank you so much for all your guys work and effort!

**Comment by Mynameisnotlenny** [comment]
Yea I on a regular basis have the issue of putting a stretcher in the back and closing the doors flexing my f3 quickly to make sure the bodies are on the stretcher in the ambulance only to get to the hospital and have the stretcher not in the back and still at the scene, the solution that works for me is holding the stretcher while driving however this doesn’t always look right as the stretcher sticks out the front of the ambulance instead of being in the back like it should be.

**Comment by PreacherDeimos** [comment]
> 

It's an Ambulance, you shouldn't have to hold the stretcher, but it's okay, I know they will fix this, just hang in there man.
