### ISSUE TITLE
2021 GMC Sierra 1500

### ISSUE THREAD

**Issue by EncrustMust** [fkk-cz/noire_vehicles#1069]
Truck needs the class changed from suv to truck because it’s only has 750 storage currently
Currently can’t use trailers
Handling is awful on it as well

**Comment by No-Yes1** [comment]
> Handling is awful on it as well

Fixed in https://github.com/fkk-cz/noire_vehicles/commit/6f1bda138f182bb24f58200809fab889fd2cb44b

> Currently can’t use trailers

We tried to use trailers on this before and they don't attach.

> Truck needs the class changed from suv to truck because it’s only has 750 storage currently

Fixed in https://github.com/fkk-cz/noire_vehicles/commit/75b75573f43eae053a0576bedc1ed6f8e823aa80. Please wait until these are merged live.
