### ISSUE TITLE
Aventador S

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire_vehicles#1121]
I just don't understand why this ticket is being closed...I had a senna that was 715k and it was hitting 205-210 at best, but for double the price of the senna at 1.5m it should be noticeably  faster. Im not saying make it hit 250 as that would be unrealistic, but at least a little better.

**Comment by Scubaaaaa** [comment]
Understandable it's double the price, but at the same time you're paying for looks and the brand. Just because a car cost double the amount of another doesn't mean it's always going to go faster. The IRL Top speed of the Senna is 208, and the IRL top speed of the Aventador S is 217. They are fairly accurate to these speeds in city.

**Comment by TdotG** [comment]
btw not to be a dick head to who ever has the Valhalla but the recent update was meant for the Valkryie and the Valhalla was buffed immensely instead

**Comment by No-Yes1** [comment]
Thanks for pointing that out. Fixed it. As for the lambo, we're not tweaking it, stop making issues about it.
