### ISSUE TITLE
Question about supporter cars/processes

### ISSUE THREAD

**Issue by Freewillie321** [fkk-cz/noire_vehicles#1192]
I saw a post last night about the 2019 ZR1. I do agree with increasing the top speed, but only to like 180-200. He had good points about how if it's worth 178k it should be improved. Also I noticed you said you can't nerf the vehicle. Nerfing is making the car worse. Buffing is making the car better. Did you mean you can't buff the ZR1? I was confused by that. Could you go more into detail on why you can't change it? It's not only the zr1, but a few others. I'm not attacking you guys. I'm just wanting a more indepth answer on how the process goes into improving the performance of a car. With supporter cars, since real money is involved, are you guys more likely to update those cars? Sorry if it's alot to ask, but I'm just curious. Also is price influenced on speed? What determines pricing of cars?

Thanks guys,
Willie

**Comment by Scubaaaaa** [comment]
As far as the ZR1 goes the person that does the tweaks has already stated he feels that it's fair for the price. The actual tweaking of vehicle doesn't matter if the vehicle is supporter or not, they make it fair to the price, the IRL performance, as well as the brand of the vehicle. Just because a car is triple the price of another doesn't mean it's going to be 3x better. The price of the car is typically based on the IRL price of the car.

**Comment by noyeahsure** [comment]
Compared to other vehicles in the price range, the vehicle performs fine, like stated in the original support, we do not want cars going above 200 in the city, and considering the fact that a lot of cars way above that price range go 180-200, like stated before. this car is decent for the price

**Comment by No-Yes1** [comment]
Just to add on to that: The vehicle itself has good, if not better then other acceleration:

https://github.com/fkk-cz/noire_vehicles/blob/2fcdd8c65e18a77762c2f11e13a0afd232b8afb1/DATA/2019zr1_data/handling.meta#L13

**Comment by No-Yes1** [comment]
The vehicle won't be tweaked. Stop making issues about it.
