### ISSUE TITLE
Missing vehicle at pdm

### ISSUE THREAD

**Issue by Gmoney7** [fkk-cz/noire_vehicles#1370]
The ninja h2 is supposedely ingame but i cant find it and no one has it in-game,

**Comment by okxeon** [comment]
The vehicle technically still is in game, but it is not available to be bought in pdm. If I had to guess it was removed back a few months ago when the oversized asset vehicles were recalled to pdm. Looking at the model right now its 244k polys which is 44k above the limit. We limit the size of vehicles because with the large number of players in the server oversized assets can lead to game freezing in high populated areas. This used to be a major issue in the downtown Los Santos area.
