### ISSUE TITLE
458 Prior

### ISSUE THREAD

**Issue by LethalTrade** [fkk-cz/noire_vehicles#1394]
I have to say putting the 488 pista sound on this car was not a good choice. The prior already had a great and unique sound. Can it please be changed back?

**Comment by okxeon** [comment]
Reverted this change here https://github.com/fkk-cz/noire_vehicles/commit/83601690d1f0c6fee6c933fc32f4048fa691947f. Was not aware not everyone was on the same page when I swapped it the first time.

**Comment by thr33o5king** [comment]
It's evident apparently the majority prefer the prior to keep this "unique" sound. Lambos Mcclarens and even GTRs have a more exotic/louder sound than this vehicle. 

The only reason I bought the Prior is because it was given the sound of the Pista. Now I have this Ferrari that doesn't sound at all like a Ferrari and do not have supporter access to trade it in and buy the Pista. 

I would have purchased the Pista otherwise. This may be a weird ask but is there anyway I can be granted access to supporter for an hour or less just to make this trade in and purchase the Pista? Id hate to have to purchase another month of supporter just to get this done.

**Comment by LethalTrade** [comment]
The current Prior sound is great. The Pista sound doesn't even sound like a Ferrari. Maybe dont buy a car for the sound next time

**Comment by thr33o5king** [comment]
Lol I didn't buy it just for the sound i bought it for the looks the stock rims and the fact that the sound change to the pista gave it a good exotic sound. Pista may not sound like a Ferrari but the current sound definitely doesn't sound like a Ferrari. Turbo flutter isn't realistic. Idle sound isn't realistic no Ferrari sounds like it's off when it's idling. Even the overrev / downshift isn't Ferrari at all.
