### ISSUE TITLE
2017 Koenigsegg Agera RS

### ISSUE THREAD

**Issue by Nicocpln** [fkk-cz/noire_vehicles#1508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For 500k its slow, with a slow acceleration, good side the handling is perfect.How is a 350k ferrari pista faster then a koenigsegg, the Koenigsegg barely goes 199-200 mph while a 350k ferrari goes 220 mph.For a koenigsegg it should atleast go 230-235 for his name.

### Expected Behavior

buff speed and acceleration

### Steps To Reproduce

Try the vehicle

### Anything else?

nope,thank you very much

**Comment by Fallinglol** [comment]
Your logic makes no sense in this scenario, "X car goes this quick so why doesn't my car go this quick"

**Comment by Nicocpln** [comment]
it does, why is a car that cost 350k faster then a car thats 500k?

**Comment by Nicocpln** [comment]
also why is a FERRARI faster then a KOENIGSEGG,so it does make sense overall

**Comment by PsychoticCore** [comment]
> also why is a FERRARI faster then a KOENIGSEGG,so it does make sense overall

They base the speeds of the cars off the prices I'm pretty sure and not the actual brand and it's IRL speed

**Comment by Nicocpln** [comment]
if they base off price, still the same thing one car is 350 the other is 500 and 20mph slower

**Comment by Fallinglol** [comment]
telling you right now from experience, they wont buff the car to go 230 lmao

**Comment by Fallinglol** [comment]
> if they base off price, still the same thing one car is 350 the other is 500 and 20mph slower

and if you really wanna go off of price your car should be well over 2 million dollars

**Comment by mfried456** [comment]
I agree with OP. For the price of the car it should go faster. It’s clear that the comparison isn’t to IRL but other cars within the city. Based on that, I think the top speed should be increased a bit (nothing too drastic) since it’s an expensive car. If top speed won’t be increased, the car should excel in other areas such as great acceleration to compensate.

**Comment by Fallinglol** [comment]
@mfried456 Maybe a buff of course, but a 30+ MPH increase is ridiculous to suggest. especially on a car that is only 500k

**Comment by BreezyEZ** [comment]
> it does, why is a car that cost 350k faster then a car that's 500k?

It's almost like there is over hundreds of cars in the city and can not fine tune each individual car to match each and every car, hence why we have imbalances.



> if they base off price, still the same thing one car is 350 the other is 500 and 20mph slower

The only reason the Pista can go that high rate of speed is whenever going downhill or getting lucky with bumps and should potentially get nerfed. But 200mph is good for a car priced at 500k, but that is just my opinion.

**Comment by Scubaaaaa** [comment]
There were reasons some cars aren't very comparable to IRL. This car was abused over and over in the past due to how good the car used to be. You can blame the people that only use the car to make sure they win. This car will not be buffed from what it does now due to the fact of it being abused in the past. You also have to think they when you buy a car you're not just paying for performance. You're also paying for the brand of the car.
