### ISSUE TITLE
2021 Ford Bronco Wildtrak Handling

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The handling on this car isn't the greatest, its feels like a boat. If a slight handling buff could happen that'd be mint

### Expected Behavior

Not to drive like a boat

### Steps To Reproduce

Drive car

### Anything else?

no

**Comment by Artificial-IQ** [comment]
Thank you for submitting a Github issue for the 2021 Ford Bronco Wildtrak. Upon thorough testing, this vehicle will not be tweaked due to the correct state that the intended handling is in. For the price and off-roading nature of this vehicle, it is where it should be at the moment. The upgrades on this vehicle were adjusted slightly here https://github.com/fkk-cz/noire_vehicles/commit/95ac7f1ea0d7bf9f4d87de816300696073e7923b
