### ISSUE TITLE
2022 Kia K5 GT

### ISSUE THREAD

**Issue by Ell34** [fkk-cz/noire_vehicles#1719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Handles like a boat. Would it be possible to give it a slight handling buff or even just swap it to the stinger handling

### Expected Behavior

it's a sedan not a huge suv, so it should handle better. 

### Steps To Reproduce

drive car

### Anything else?

no

**Comment by Competent1** [comment]
Thank you for submitting this issue on the 2022 Kia K5 GT and waiting patiently. During the time that has passed since this issue has made, this vehicle has undergone a lot of testing and a lot of different adjustments/tweaks. The adjustments that should fix this issue have been made here https://github.com/fkk-cz/noire_vehicles/commit/ffdc5d7c2c9f13c657d8147b436621911f731cbb. If there are further issues with this vehicle (the adjustments/tweaks made here don't fix the issue, other issues arise, etc.) then please feel free to submit another issue regarding the vehicle so this vehicle can be tested again. This also applies to any other vehicle in city. Again, thanks for your patience on this and please wait for the adjustments/tweaks to get merged.
