### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2022 BMW M5 competition

### ISSUE THREAD

**Issue by ColeFiveM** [fkk-cz/noire_vehicles#1748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I get in or out of the bmw it makes me go through the passenger side

### Expected Behavior

To let me get out/in of the driver door

### Steps To Reproduce

1. Get in or out of the car.
2. You see it only lets you out of the passenger side

### Anything else?

N/A

**Comment by Competent1** [comment]
Thank you for making this issue on the 2022 BMW M5 Competition. This vehicle has undergone tests to try and replicate the issue you have stated here. I have gotten in and out of this vehicle 20+ times, all through the driver side door. It has not made me go through the passenger side door to enter the vehicle like you have said it does in this issue. I have been able to enter this vehicle through the driver side door and when exiting, I exit through the same driver side door. Do make sure there are no obstructions that would be blocking the driver side door, otherwise players will have to enter/exit through the passenger door to get to the drivers seat (makes sense and applies to most vehicles). No action will be taken on this as it has been deemed that this isn't an issue after testing. Do provide a video of this issue occurring in the future if this is still an issue for you as I was not able to replicate this issue with said vehicle. Thanks!
