### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: McLaren 570s Vorsteiner

### ISSUE THREAD

**Issue by Etched6477** [fkk-cz/noire_vehicles#1753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the handling on this vehicle is just absolutely atrocious. The tires spin for around 3 seconds before gripping the ground upon launch & it just slip and slides all over the place when driving.  I would like the handling to be tweaked some.

### Expected Behavior

Better handling & better traction.

### Steps To Reproduce

Drive the car.

### Anything else?

Nothing else.

**Comment by Competent1** [comment]
Thank you for submitting this issue on the McLaren 570s Vorsteiner. This vehicle has been tested many times since you've made this issue and a lot of adjustments were made on this vehicle. The issues that you have brought up regarding this vehicle have been fixed here https://github.com/fkk-cz/noire_vehicles/commit/c67c4db1dc3d867213e0084e22007a0696642f38. Wait for this tweak to be merged. Thanks for being patient and if there happen to be more issues with this vehicle (or any vehicle), please do make another issue so we can look at it!
