### ISSUE TITLE
Looking to buff the 575k Bugatti Bolide speed/acceleration 

### ISSUE THREAD

**Issue by sirgold1** [fkk-cz/noire_vehicles#176]
I recently upgraded my membership to be able to buy the Bugatti Bolide and was quite disappointed with the performance of the vehicle. It gets to 130 no problem but struggles to gain further momentum in speed, I'd assume it would go at least 200+ in top speed since the irl car goes up to 310 mph. In terms of pricing as well the speed for it simply does not add up as I am easily losing in speed/acceleration to a $50,000 Maserati and plenty of other cars that are half or even a third the price of the Bugatti. I hope to see an increase in speed/acceleration as I have dedicated many hours to earn enough to afford the car. 

Hopefully this isn't an impossible request! Thanks in advance for your guys support.

**Comment by GunnaWunnaa** [comment]
I was also looking to upgrade my patreon to diamond or gold to purchase the supporter vehicles, however it seems like too many of the supporter vehicles aren't worth their price especially this Bugatti. You would expect that since this car costs 575k and it requires a gold supporter tag it would easily surpass any other car that is cheaper.
