### ISSUE TITLE
mercedes-AMG GT 63 S 

### ISSUE THREAD

**Issue by Etched6477** [fkk-cz/noire_vehicles#1788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I feel like this vehicle should have the speed adjusted. The vehicle currently max's out at 120.

### Expected Behavior

Speed should be higher then what it is currently.

### Steps To Reproduce

Drive the car.

### Anything else?

No.

**Comment by Artificial-IQ** [comment]
Thank you for submitting this issue for the Mercedes-AMG GT 63 S. I just tested this vehicle and reached speeds of 150mph on flat land and 180mph hitting the bumps on LS freeway past lower pillbox. Make sure you upgrade the vehicle, as the 120mph top speed (which you referred to above) is the non-upgraded state of this vehicle. This vehicle will not be receiving a change due to being a 4-door vehicle that is $211,900, it is where it should be in its current state. Have a nice day.
