### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: FORD MUSTANG GT

### ISSUE THREAD

**Issue by bigarabb** [fkk-cz/noire_vehicles#1795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The car is just to slow, needs a buff

### Expected Behavior

i am expecting a buff of the speed on this car just doesn't make any sense i know this car can reach over 150 mph with a limiter and without a limiter over 181 mph. i own one myself (irl), the sound is amazing and hella realistic just the speed only 120 mph is crazy. If not then if you guys can make the same model just a different one with a different price thats a lil faster would be great.

### Steps To Reproduce

just buff the speed 

### Anything else?

no

**Comment by Artificial-IQ** [comment]
Thank you for submitting this issue on the Ford Mustang GT. After testing I found that the overall drivability of the vehicle is fine. Regarding top speed, weren't aren't going to 100% mimic IRL top speeds of vehicles due to the size of the map. Considering the $49,638 price tag at PDM and the fact you can get it even cheaper at UCL, the top speed is where it should be. I see you mentioned another model should be added for this specific car. There is a supporter option which is the Mustang Shelby GT500 and of course it's not the same vehicle but it's still something you should look into. This vehicle's speed will not be changed. Have a nice day.
