### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 

### ISSUE THREAD

**Issue by Ermal182** [fkk-cz/noire_vehicles#1811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Bmw m5 f90 the regular one not the supporter its so slow 

### Expected Behavior

I think it should be faster

### Anything else?

No

**Comment by Artificial-IQ** [comment]
Thank you for submitting this issue for the 2018 BMW M5 F90 (Non-Supporter). This vehicle has been abused due to it being a 4-door car which resulted in less rp. Also, regarding the quality of life changes, this car is not slow by any means, so I don't really understand you saying 'its so slow'. You can compare it to other sedans near its price range and it is fair. After testing, this vehicle is where it should be in its current state and will not be changed. Have a nice day.
