### ISSUE TITLE
Ninja H2 leanback nerf 

### ISSUE THREAD

**Issue by natenectar** [fkk-cz/noire_vehicles#1912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

guys you can't even get both feet on the bike before the front end starts to go back down, if you want to adjust it for a new life rule, that's all fine and dandy, but cmon, this bike is supposed to have 1000 cc, if i dumped the clutch after high revs sitting still on this bike, I think it has enough power for the front end to get higher than a foot off the ground.. The trade off from holding a wheelie is wrecking, sure you can pop a wheelie to go faster, but your also greatly increasing your chances of wrecking because you can't control it 

### Expected Behavior

I expect a 1000cc sports bike to be able to pop a wheelie higher than 1 foot off the ground for longer than 2-3 seconds 

### Anything else?

I just think it got hit a little to hard, its just discouraging seeing cars/bikes in the city that i love, for things like this to happen to, I understand people abuse these things, and i understand when this happens over and over again, it needs to be talked about and looked at, but I feel as if this adjustment was just hit a little to hard, and i am requesting someone goes back and test the leanback for the H2, on a flat road, uphill, and downhill

**Comment by Artificial-IQ** [comment]
Thank you for submitting a GitHub issue for the Kawasaki Ninja H2. After thorough testing of all sports bikes, dirt bikes, and even the LEO bikes, we have determined that we will be removing wheelies entirely. Doing wheelies on bikes sounds good on paper. The issue was the fact that individuals were simply popping a wheelie to get a speed boost. There’s no way to prevent that curb boosting. So in an RP sense, the only logical way to prevent them from abusing this was to remove it entirely. 

Furthermore, the optimal solution wouldn't be to nerf acceleration/top end and keep the wheelie. If you have to take a turn or go through bends, the bike would be significantly slower. Bikes would be able to wheelie in a straight line but would feel extremely sluggish when cornering.

After thorough testing and review, we have decided that the Ninja H2 is fair in its current state and will not be changed. Have a nice day.
