### ISSUE TITLE
[Exact name of vehicle, as displayed in game]: 2020 Mercedes-Benz AMG GT Black

### ISSUE THREAD

**Issue by bodega67** [fkk-cz/noire_vehicles#1920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the car was nerfed last night by 50 mph.  Now giving it a total top speed of 125mph.  I believe this is wayy to low.  The mustang gt goes the same speed for the cost of 50ish thousand dollars.  This car cost 349k.  I just believe that making the top speed 125mph is not satisfactory.  The car in real life is of course capable of much higher speeds than that and i believe how it was before was a much more accurate representation of how it really should be

### Expected Behavior

Please raise the top speed back up because in all honestly the car is pretty much ruined.  Its a super car and should be able to attain much higher speeds than a ford mustang gt.

### Steps To Reproduce

just drive the car down the freeway

### Anything else?

no

**Comment by Artificial-IQ** [comment]
Thank you for submitting a GitHub issue for the 2020 Mercedes-Benz AMG GT Black. This vehicle was tweaked in order to maintain the integrity of vehicle balance. The intended speed is now where it should be as we will be pushing out a massive quality-of-life wave for this year. No need to worry as this is not only your vehicle being affected. 

There are positives that come out of this such as cleaner chases, less unrealistic collisions, smoother driving, and armor will be set to 2x of its current state. Thank you for your patience as this process will take a while and each and every car will be tested and tweaked accordingly. I also must mention that LEO vehicles will be in line with these vehicle changes. Everything will be lowered in accordance with the fair economy of vehicles and the size of the map. Have a nice day.
