### ISSUE TITLE
Tesla Roadster

### ISSUE THREAD

**Issue by Jayson1800** [fkk-cz/noire_vehicles#353]
Hello,

I had the Tesla Roadster for one whole day now, The acceleration is very good for the car, but everything else is bad. The turning, brakes, and especially the top speed. The top speed in real life is 250+ mph and in the city is 145. I think the top speed should be higher, at least 220 or 200 mph. The braking and the turning could be better. The braking is horrible, it takes way too long to fully stop the car. If your going the top speed rn 140mph, its hard to brake and the chances of hitting to other cars and buildings are very high. 

Recommend: 
Fix the top speed 
Brakes
Turning

https://www.tesla.com/roadster

**Comment by Jayson1800** [comment]
And no neons on the bottom

**Comment by fkk-cz** [comment]
The roadster in game is the second generation https://en.wikipedia.org/wiki/Tesla_Roadster_(second_generation) model which is not even available yet, with a _claimed_ top speed of 250 MPH.. Putting aside whether these numbers are actually true, in reality no one would be able to drive at those speeds on a public road due to traffic, road conditions, and tire quality.

As a result, the roadster's performance is going to be based off the first generation, which has an _actual_ top speed of 125-130 MPH.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/2bc91cd8b525a9adef5a97a17404af52ae7fc907#diff-66b8bbdab284f7f1604dbc52076f758be40827ce8ebebcdb08534b1d8dd49b9c

fixed the braking and improved the handling slightly

**Comment by Jayson1800** [comment]
But there are some videos of the roaster going against a Bugatti on a track at least, beating the Bugatti. Can you at least boost the top speed like at 175-180 to make it reasonable? And I paid 200,000 dollars for the car, I could have got something else. If you can't do that, can I get a full refund then?

**Comment by Jayson1800** [comment]
https://www.youtube.com/watch?v=f2H1l9EzGQ8
https://www.youtube.com/watch?v=53WrZqIc4aw

**Comment by Jayson1800** [comment]
https://www.youtube.com/watch?v=05GPjfJ1vQU

**Comment by Jayson1800** [comment]
in the tesla vs LeFerrari, the tesla beat the Ferrari. The LaFerrari top speed is 350 km/h (220mph). So the roadster is faster than the Ferrari.
