### ISSUE TITLE
2021 BMW M4 Competiton

### ISSUE THREAD

**Issue by Danny01190** [fkk-cz/noire_vehicles#629]
The cars acceleration and speed is fine and the braking isn't to bad, but the turning is horrible and definitely should be improved as it can barely turn.

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/cad55a3df68b34a3e2aed00c436b9a94a428125f#diff-db2e700b34f1c81e99d46a6538e129e1c6e2bcc32c9cecff95802f27a0008970

Drove the vehicle a bit, looks like the issue is the vehicle losing traction at a small distance above the ground. Traction values look fine otherwise.

**Comment by Danny01190** [comment]
So will anything be done to it?

**Comment by fkk-cz** [comment]
> 
> 
> So will anything be done to it?

already done. There also seems to be too much body roll/weight transfer when turning/accelerating. This is fixed as well.
https://github.com/fkk-cz/noire_vehicles/commit/9b3d6796026db41df36835b258874cd6adae3348#diff-db2e700b34f1c81e99d46a6538e129e1c6e2bcc32c9cecff95802f27a0008970

**Comment by Danny01190** [comment]
Yea that's what I felt the turning felt very heavy, thanks for fixing it loved everything about the car just could not turn for shit.
