### ISSUE TITLE
vehicle refund on 2 cars. 

### ISSUE THREAD

**Issue by Archerr95** [fkk-cz/noire_vehicles#831]
the tesla roadster will not drive after using a repair kit on it (but it will work if you give someone else the keys???) rendering it near enough useless, therefore if i cant use the car then i feel like im entitled to a refund on it. 

Mclaren F1, this car is a mess XD no armour upgrades so if you hit a stop sign the car is smoking, the doors dont work, when you step out of the car you can walk straight through it. when you try and enter the car you just sprint at the side for a bit and hope it lets you in... or you just bounce off and have to lock/unlock multiple times before it MIGHT let you in... its just extremely unrealistic and massive "fail RP" when using it. 

https://medal.tv/games/gta-v/clips/6M5fZmZILxpnI/d1337RAIAanp?invite=cr-MSx6NU4sMjY1NzEwMjIs

**Comment by No-Yes1** [comment]
> the tesla roadster will not drive after using a repair kit on it (but it will work if you give someone else the keys???) rendering it near enough useless, therefore if i cant use the car then i feel like im entitled to a refund on it.

Ez fix for this, is to fill it up with gas one time, then you should be good.

> Mclaren F1, this car is a mess XD no armour upgrades so if you hit a stop sign the car is smoking, the doors dont work, when you step out of the car you can walk straight through it. when you try and enter the car you just sprint at the side for a bit and hope it lets you in... or you just bounce off and have to lock/unlock multiple times before it MIGHT let you in... its just extremely unrealistic and massive "fail RP" when using it.

Need to test a different layout on this possibly. you can only do it if the door is open. I'll test a diff. layout and see

**Comment by Archerr95** [comment]
did you find a different layout, the tesla fix was great thankyou! but the lack of armour and just how tedious the f1 is, it just unusable

**Comment by No-Yes1** [comment]
Not yet I'm afraid, due to r* limitations, there are no vehicle layouts for middle seat drivers, it is like the Tesla Semi. In regards to the armour etc, I've taken a look into this and can confirm that the values were way too high. This has now been sorted and brought down to normal values https://github.com/fkk-cz/noire_vehicles/commit/31d875fd76ff7f1a0851a092ab80599e040a20e9. As per the issue with you walking through the inside of the car, this only occurs if the door is open, which indicates a model issue and something that keeps re-occuring with "butterfly doors" (i.e ``p1``), unsure what is the main cause of it (possibly just no collisions, who knows lol). I'll keep looking and maybe find one more suitable and get back to you before this commit merges with the master branch.

**Comment by Archerr95** [comment]
do you then think a refund is feasible due to the buggy nature of the car, and how unreliable and borderline unusable it can be especially in a hurry. especially if its an issue that can never be fixed.

**Comment by No-Yes1** [comment]
apologies on the delay of responding on this one, This car is being recalled, so I would imagine you would have sold it back to PDM by now at the recalled rate/normal rate.
