### ISSUE TITLE
LSPD HS vechiles 

### ISSUE THREAD

**Issue by SavageStonerDude** [fkk-cz/noire_vehicles#837]
okay so after becoming cert'd with the mustang and trying to pass the Camaro cert.. i truly think that the mustang needs a top speed buff (at least to match the highways unmarked charger top speed).. it seem kinda pointless to have a high-speed car that gets out ran by basically all of HPs cars.. high-speed shouldn`t have to call on a trooper for a faster vehicle imo.. and the Camaro has GREAT acceleration bt the braking and turning is extremely inconsistent for some reason.. id really like it to drive like the supra or even the nonsupport GTR bt keep the lower top speed for sure.. i know that phin has brought up a few of these concerns before bt after truly driving these cars for myself i cant help bt think they could use a little bit of love especially with the new robbery system and with how fast crims can finish the robbery and get in the car than just roll out fast asf or even when compared to hps unmarked and even marked chargers.. id really like to see our high-speed cars have more of a chance without having to depend on hp every time a super-car commits a crime.. just my honest opinion after driving the high-speed cars for over a week now

**Comment by No-Yes1** [comment]
As stated in the HS ticket, The Mustang is an muscle car... Ofc it's going to spin out at corners... So that won't get fixed. As for the camaro, the braking is fine. I've tweaked the corners slightly so that should improve that portion. But again, the Camaro is also a semi muscle/semi sports vehicle, and it's already AWD so not going to just tweak it so there is no issues with anything at all... Change has been reflected in https://github.com/fkk-cz/noire_vehicles/commit/16a32a4007f74bfec5f53e497af2d5d0828277bc. It's also dependant on the driver on the HS vehicle. I've spoken and seen a few times when a HS vehicle is just driving so poorly which is the reason why the vehicle "is inconsistent". There will be no further changes to any HS vehicle. The Mustang was meant to SAHP however because of how poorly the Camaro drove / handled. It was passed back to LSPD for the time being....
