### ISSUE TITLE
1969 VW Class 5

### ISSUE THREAD

**Issue by MostJabrone** [fkk-cz/noire_vehicles#852]
You take massive amounts of damage when crashing in this vehicle. Crashed into a pole at like 50mph and went from 100 to 0 HP.

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/commit/52f85822447c563962e6ad78ea93979dd278f084 - Reverted a commit I made a while back when I made the ATV bikes have motorcycle vehicle class due to people exploting it at drug areas. Now the new change that requires a vehicle to have an openable boot is live, there isn't a need for them to still have the motorcycle class. Hopefully this should increase damage. Please wait a few days for this to merge.
