### ISSUE TITLE
Lamborghini Huracan Spyder (Not Evo)

### ISSUE THREAD

**Issue by apricates** [fkk-cz/noire_vehicles#860]
Sorry for making this issue again but i couldn't message in the old one but since there were two files for lp610 the correct one has a fInitialDriveMaxFlatVel value="159.381711" which is really slow for a 418k lambo and the 105k Hellcat has a drivemax of 215.

**Comment by No-Yes1** [comment]
But the vehicle has a good top speed, no?

**Comment by No-Yes1** [comment]
https://github.com/fkk-cz/noire_vehicles/blob/5207fde6139749ee314d4883c9ad47f90ad54d12/DATA/lp610_data/handling.meta#L17

that's the correct top speed, which is almost 200, give or take. Which is on par with how it should be. Don't be alarmed by the rest of it. since it works fine right now. I'm guessing because the files were duplicated in here (unsure if it's duplicated in the server), that _could_ have been the reason why the audio hash was different

**Comment by apricates** [comment]
The top speed is 190ish with like the bumps on the freeway but without that its actually pretty slow. I thought the LP610 file was the correct one since it has the latest change for the audio hash not the LP610_DATA.

**Comment by No-Yes1** [comment]
to finish this up, i've removed the old / conflicted lp610 file. Meaning that the only file is the correct one "LP610_Data". This should stop the conflicted issue with the audio hash.
