### ISSUE TITLE
2019 Mclaren Senna

### ISSUE THREAD

**Issue by apricates** [fkk-cz/noire_vehicles#866]
Hey I was wondering if you guys can make the top speed a bit higher as its kinda slow for 715k. The dodge viper goes 230 and is only 465k. The Senna on flat ground goes 180 while the demon and viper go over 200+. Thank you in advance.

**Comment by No-Yes1** [comment]
Not sure why the Viper went 230... took a closer look and i'm guessing it was because of the drag values. I have increased that as well as tweaked the Senna. Please wait for a few days for this to merge. https://github.com/fkk-cz/noire_vehicles/pull/868/commits/d9ff689646ec16583c507477217713c9ed3c688b
