### ISSUE TITLE
Tesla Roadster

### ISSUE THREAD

**Issue by HeywoodJabloughmi** [fkk-cz/noire_vehicles#867]
I just purchased a tesla roadster because of the hype in the big city, and after buying it, i noticed it has some issues. its rear wheel drive, and in the big city, its all wheel drive. also the top speed is 156, in the big city its 255. and the handling on it is just garbage in general. the tires are huge on that thing, it should not spin all over like that. and the wheel spin is not realistic. its electric, and with the technology of the sensors it would detect wheel spin and adjust power output accordingly, maximizing performance. its not like its a 1969 charger, with massive amounts of horsepower with no retarders. please fix this. please and thankyou.

**Comment by No-Yes1** [comment]
> rear wheel drive, and in the big city, its all wheel drive. 

Interesting, I already tweaked this recently: https://github.com/fkk-cz/noire_vehicles/pull/838/commits/c3450023ee087c25170fedba85806dd1c39032f0. I'll have to investigate that a little further.

> also the top speed is 156, in the big city its 255.

There is no way, the vehicle will go up to 255....... People will abuse it due to the price point where it's at. The issue is, is how semi easy it is to make money and the way players exploit ways (i.e paying for In-game cash for IRL money), it's hard to tweak values etc etc.

In reagrds to the wheelspin, this has been fixed in https://github.com/fkk-cz/noire_vehicles/pull/868/commits/153c71eef383f9ecdbeb797bce512dcb3ac523a4 hopefully. please wait for a few days for this to merge live.
