### ISSUE TITLE
Tesla Cyber truck

### ISSUE THREAD

**Issue by Jamalcandog** [fkk-cz/noire_vehicles#889]
Recall the dumb Tesla cyber truck! It need's gas windows are broken, Lights are buggy, Paint is buggy, Shi see through a when you break a door or something, Glass don't break, turns like a garbage truck, only 2 seats When it has 6. Surprised it's been in the city for this long!

**Comment by No-Yes1** [comment]
let me debug this mess:

 >  It need's gas 

this is a common thing with _most_ electric vehicles, see this issue on the public repo https://github.com/fkk-cz/noire-public/issues/449

> windows are broken, Lights are buggy, Paint is buggy, Shi see through a when you break a door or something, Glass don't break,

Seems like a texture issue, use this issue #888.

>turns like a garbage truck

Fixed in https://github.com/fkk-cz/noire_vehicles/commit/182ccea4ebde6458d5a4a5162bf0fa2abf1edd08. Please wait a few days for it to merge.

> only 2 seats When it has 6. Surprised it's been in the city for this long!

I have attempted to fix this numerous times, however the model creator has only made it so you can only seat 2 people, not much we can do.

If you don't like the vehicle, you can sell it back to PDM, you also have the test drive option so half the issues you've reported would've been known to us.

**Comment by fkk-cz** [comment]
Recalled this vehicle earlier this morning.

**Comment by No-Yes1** [comment]
Reverted the commit: https://github.com/fkk-cz/noire_vehicles/commit/6e06c9602acecdc4f837ae7fb3b58b90273c2592
