### ISSUE TITLE
2011 Subaru Impreza STI

### ISSUE THREAD

**Issue by EncrustMust** [fkk-cz/noire_vehicles#968]
Theres multiple things wrong with this vehicle
-Cant change the wheels/or change the color of the stocks
-Suspension is broken so whenever you turn you roll
-Cant put any upgrades on it so its insanely slow
-Breaks down way too easily

**Comment by No-Yes1** [comment]
> -Cant change the wheels/or change the color of the stocks
> -Cant put any upgrades on it so its insanely slow
This could either be a model issue/modkit issue:  fixed in https://github.com/fkk-cz/noire_vehicles/commit/5ae9aa7af933143d8556fff2b0c2ae419df0f99c.

> -Suspension is broken so whenever you turn you roll
Attempted to fix in https://github.com/fkk-cz/noire_vehicles/commit/93e9296069089d2ec165f5b941891314f5d8d9ea.

Please wait for a few days for this to merge live.
